Asn1_verbosity = "none";
ORUs = (
{
  tx_bw              = [106];
  rx_bw              = [106];
  carrier_tx         = [4049760];
  carrier_rx         = [4049760];
  prach_config_index = 159;
  prach_msg1_start   = 0;
  tdd_period         = 5;
  num_dl_slots       = 3;
  num_dl_symbols     = 6;
  num_ul_slots       = 1;
  num_ul_symbols     = 4;
  numerology         = 1;
  tp_cores           = [-1];
  num_tp_cores       = 1;
  ru_thread_core     = 9
});
RUs = (
{
  local_rf       = "no";
  nb_tx          = 1;
  nb_rx          = 1;
  att_tx         = 0;
  att_rx         = 0;
  bands          = [77];
  max_pdschReferenceSignalPower = -27;
  max_rxgain     = 75;
  sf_extension   = 0;
  eNB_instances  = [0];
  sl_ahead       = 6;
  tr_preference  = "raw_if4p5";
  do_precoding   = 0;
});
log_config :
{
  global_log_level = "info";
  hw_log_level     = "info";
  phy_log_level    = "info";
  mac_log_level    = "info";
  rlc_log_level    = "info";
  pdcp_log_level   = "info";
  rrc_log_level    = "info";
  ngap_log_level   = "info";
  f1ap_log_level   = "info";
};
fhi_72 = {
  dpdk_devices = ("0000:01:01.0", "0000:01:01.1");
  system_core  = 6;
  io_core      = 7;
  worker_cores = (8);
  du_addr      = ("00:11:22:44:54:00", "00:11:22:44:54:01");
  mtu          = 9600;
  file_prefix  = "ru";
  app_id       = "RU";
  fh_config = ({
    Ta3_up    = (50, 350);
    T1a_cp_dl = (285, 470);
    T1a_cp_ul = (285, 429);
    T1a_up    = (300, 450);
    Ta4       = (400, 440);
    T2a_up    = (350, 1200);
    ru_config = {
      iq_width       = 16;
      iq_width_prach = 16;
    };
  });
};
