// SPDX-License-Identifier: LicenseRef-CSSL-1.0
//
// hexdsp_offload_imp.c — DSP-side skeleton implementation.
//
// This file is compiled with hexagon-clang and loaded by FastRPC into the
// Compute DSP (cDSP) protected domain at runtime.  The ARM stub calls
// hexdsp_offload_process(); FastRPC unmarshalls the call and invokes
// hexdsp_offload_run() here on the DSP.
//
// Useful DSP headers:
//   HAP_farf.h   — logging (FARF macro, visible via: adb logcat -s adsprpc)
//   HAP_mem.h    — DSP-side heap allocation
//   hexagon_types.h / hexagon_protos.h — HVX intrinsics
//
// To enable HVX vector processing, compile with:
//   -mhvx -mhvx-length=128B
// and #include <hexagon_types.h>.

#include "hexdsp_offload.h"   // generated by qaic
#include "HAP_farf.h"
#include <stdlib.h>
#include <string.h>

// ---------------------------------------------------------------------------
// Session lifecycle — called by FastRPC on remote_handle64 open/close.
// ---------------------------------------------------------------------------

int hexdsp_offload_open(const char *uri, remote_handle64 *handle)
{
    // Allocate a small context token; the value is opaque to FastRPC.
    void *ctx = malloc(sizeof(int));
    if (!ctx)
        return -1;
    *handle = (remote_handle64)(uintptr_t)ctx;
    FARF(RUNTIME_HIGH, "hexdsp_offload: session opened (handle=%p)", ctx);
    return 0;
}

int hexdsp_offload_close(remote_handle64 handle)
{
    free((void *)(uintptr_t)handle);
    FARF(RUNTIME_HIGH, "hexdsp_offload: session closed");
    return 0;
}

// ---------------------------------------------------------------------------
// Main compute entry point.
//
// in_buf / out_buf are DMA-mapped by FastRPC from the ARM rpcmem buffers;
// they arrive as ordinary pointers here — no extra mapping needed.
// ---------------------------------------------------------------------------

int hexdsp_offload_run(remote_handle64 handle,
                        const uint8_t  *in_buf,  int in_bufLen,
                        uint8_t        *out_buf, int out_bufLen)
{
    FARF(RUNTIME_HIGH,
         "hexdsp_offload_run: in=%d out=%d bytes", in_bufLen, out_bufLen);

    // -----------------------------------------------------------------------
    // TODO: replace this passthrough with the actual Hexagon kernel.
    //
    // Scalar example:
    //   for (int i = 0; i < out_bufLen && i < in_bufLen; i++)
    //       out_buf[i] = in_buf[i] ^ 0xff;
    //
    // HVX vector example (requires -mhvx -mhvx-length=128B):
    //   #include <hexagon_types.h>
    //   HVX_Vector *vin  = (HVX_Vector *)in_buf;
    //   HVX_Vector *vout = (HVX_Vector *)out_buf;
    //   int nvec = in_bufLen / VLEN;  // VLEN = 128 for 128B HVX
    //   for (int i = 0; i < nvec; i++)
    //       vout[i] = Q6_V_vnot_V(vin[i]);  // bitwise NOT as placeholder
    // -----------------------------------------------------------------------
    int len = (out_bufLen < in_bufLen) ? out_bufLen : in_bufLen;
    memcpy(out_buf, in_buf, len);

    return 0;
}
