// SPDX-License-Identifier: LicenseRef-CSSL-1.0
//
// hexdsp_offload_arm.c — ARM-side glue library.
//
// This .c file is compiled into libhexdsp_offload.so (with the qaic-generated
// hexdsp_offload_stub.c).  OAI loads it at runtime via load_module_shlib /
// dlopen, resolving the three symbols below:
//
//   hexdsp_offload_init()     — open FastRPC session, initialise rpcmem
//   hexdsp_offload_shutdown() — close session, release rpcmem
//   hexdsp_offload_process()  — DMA-map buffers, call DSP, copy result back
//
// The caller owns the in/out memory; this glue handles the RPCMEM bounce
// buffers internally so that the DSP always sees physically-contiguous ION
// memory regardless of how OAI allocated the working buffers.
//
// FastRPC docs: Hexagon SDK → ipc/fastrpc/
// RPCMEM docs:  Hexagon SDK → ipc/fastrpc/rpcmem/

#include "hexdsp_offload.h"   // generated by qaic from hexdsp_offload.idl
#include "rpcmem.h"
#include <stdint.h>
#include <string.h>
#include <stdio.h>

// Domain: CDSP = 3, ADSP = 0. The cDSP is the compute DSP on SA9000P.
#define HEXDSP_DOMAIN  3

static remote_handle64 dsp_handle = (remote_handle64)-1;
static int             rpcmem_ready = 0;

// ---------------------------------------------------------------------------
// hexdsp_offload_init — open FastRPC session.
// Called once by OAI at startup (maps to LDPCinit() in the LDPC pattern).
// ---------------------------------------------------------------------------
int hexdsp_offload_init(void)
{
    // Build the URI: module name + domain selector.
    // The skel library must be present on the device at:
    //   /vendor/lib/rfsa/adsp/libhexdsp_offload_skel.so
    char uri[256];
    snprintf(uri, sizeof(uri),
             "%s&_dom=%d", hexdsp_offload_URI, HEXDSP_DOMAIN);

    int err = hexdsp_offload_open(uri, &dsp_handle);
    if (err) {
        fprintf(stderr, "hexdsp_offload_open failed: %d\n", err);
        return err;
    }

    rpcmem_init();
    rpcmem_ready = 1;
    return 0;
}

// ---------------------------------------------------------------------------
// hexdsp_offload_shutdown — tear down.
// ---------------------------------------------------------------------------
int hexdsp_offload_shutdown(void)
{
    if (dsp_handle != (remote_handle64)-1) {
        hexdsp_offload_close(dsp_handle);
        dsp_handle = (remote_handle64)-1;
    }
    if (rpcmem_ready) {
        rpcmem_deinit();
        rpcmem_ready = 0;
    }
    return 0;
}

// ---------------------------------------------------------------------------
// hexdsp_offload_process — main offload entry point.
//
// in/out are OAI-allocated buffers (e.g. stack or malloc).  We bounce them
// through rpcmem-allocated ION buffers so FastRPC can DMA-map them to the
// DSP without an extra copy inside the kernel.
// ---------------------------------------------------------------------------
int hexdsp_offload_process(const uint8_t *in,  uint32_t in_len,
                            uint8_t       *out, uint32_t out_len)
{
    int err = 0;

    uint8_t *rpc_in  = rpcmem_alloc(RPCMEM_HEAP_ID_SYSTEM,
                                     RPCMEM_DEFAULT_FLAGS, in_len);
    uint8_t *rpc_out = rpcmem_alloc(RPCMEM_HEAP_ID_SYSTEM,
                                     RPCMEM_DEFAULT_FLAGS, out_len);
    if (!rpc_in || !rpc_out) {
        fprintf(stderr, "hexdsp_offload: rpcmem_alloc failed\n");
        err = -1;
        goto cleanup;
    }

    memcpy(rpc_in, in, in_len);

    // FastRPC call: transfers rpc_in/rpc_out to the DSP via DMA.
    err = hexdsp_offload_process(dsp_handle,
                                  rpc_in,  (int)in_len,
                                  rpc_out, (int)out_len);
    if (err) {
        fprintf(stderr, "hexdsp_offload_process RPC failed: %d\n", err);
        goto cleanup;
    }

    memcpy(out, rpc_out, out_len);

cleanup:
    if (rpc_in)  rpcmem_free(rpc_in);
    if (rpc_out) rpcmem_free(rpc_out);
    return err;
}
