// SPDX-License-Identifier: LicenseRef-CSSL-1.0
//
// hexdsp_offload_arm.c — ARM-side glue library.
//
// This .c file is compiled into libhexdsp_offload.so (with the qaic-generated
// hexdsp_offload_stub.c).  OAI loads it at runtime via load_module_shlib /
// dlopen, resolving the three symbols below:
//
//   hexdsp_offload_init()     — open FastRPC session, initialise rpcmem
//   hexdsp_offload_shutdown() — close session, release rpcmem
//   hexdsp_offload_process()  — copy to ION buffers, call DSP, copy result back
//
// The caller owns the in/out memory; this glue handles the rpcmem bounce
// buffers internally so the DSP always sees physically-contiguous ION memory
// regardless of how OAI allocated the working buffers.
//
// Validated on DragonWing SA9000P / IQ-9075 with fastrpc 1.0.4 (Linux HLOS).
//
// FastRPC docs: Hexagon SDK → ipc/fastrpc/
// RPCMEM docs:  Hexagon SDK → ipc/fastrpc/rpcmem/

#include "hexdsp_offload.h"   // generated by qaic from hexdsp_offload.idl
#include "remote.h"           // DSPRPC_CONTROL_UNSIGNED_MODULE, remote_session_control
#include "rpcmem.h"
#include <stdint.h>
#include <string.h>
#include <stdio.h>

// Maximum buffer sizes for the pre-allocated ION bounce buffers.
// Set these to the largest buffers your workload will ever pass in a single
// hexdsp_offload_process() call.  Pre-allocating at init time avoids
// per-call rpcmem_alloc/free cycles that exhaust the pool on high-call-rate
// workloads (e.g. per-codeword LDPC decode loops).
#define HEXDSP_MAX_IN_LEN   (64 * 1024)   // TODO: adjust for your workload
#define HEXDSP_MAX_OUT_LEN  (64 * 1024)   // TODO: adjust for your workload

static remote_handle64 dsp_handle   = (remote_handle64)-1;
static int             rpcmem_ready = 0;
static uint8_t        *g_rpc_in     = NULL;
static uint8_t        *g_rpc_out    = NULL;

// ---------------------------------------------------------------------------
// hexdsp_offload_init — open FastRPC session and pre-allocate ION buffers.
// ---------------------------------------------------------------------------
int hexdsp_offload_init(void)
{
    // Guard: test harnesses often call init() before every work unit to reset
    // state.  Re-opening the session and re-allocating ION buffers on every
    // call exhausts the rpcmem pool within a few hundred invocations.
    if (dsp_handle != (remote_handle64)-1)
        return 0;

    // On Linux HLOS with fastrpc >= 1.0.4 the secure cDSP device is used by
    // default, which requires signed skels.  Enable unsigned-PD mode so that
    // custom skels can be loaded without a hardware signature.
    // MUST be called before the first remote_handle64_open() call.
    struct remote_rpc_control_unsigned_module um = { .domain = 3, .enable = 1 };
    int rc = remote_session_control(DSPRPC_CONTROL_UNSIGNED_MODULE, &um, sizeof(um));
    if (rc)
        fprintf(stderr, "hexdsp_offload: remote_session_control(UNSIGNED_MODULE) returned %d (continuing)\n", rc);

    // rpcmem_init() opens /dev/dma_heap/system so libcdsprpc.so can DMA-transfer
    // the FastRPC shell to the DSP during remote_handle64_open() below.
    // MUST be called before hexdsp_offload_open().
    // NOTE: rpcmem.a must NOT be linked (see CMakeLists.txt); rpcmem symbols
    // come from the device's libcdsprpc.so.
    rpcmem_init();
    rpcmem_ready = 1;

    // "&_dom=cdsp" selects the Compute DSP on Linux HLOS (fastrpc >= 1.0.4).
    // Use the string form rather than "&_dom=3" — more readable and robust
    // across SDK versions.
    const char *uri = hexdsp_offload_URI "&_dom=cdsp";

    int err = hexdsp_offload_open(uri, &dsp_handle);
    if (err) {
        fprintf(stderr, "hexdsp_offload_open failed: %d\n", err);
        rpcmem_deinit();
        rpcmem_ready = 0;
        return err;
    }

    // Pre-allocate ION-backed bounce buffers once; reuse across all process() calls.
    g_rpc_in  = rpcmem_alloc(RPCMEM_HEAP_ID_SYSTEM, RPCMEM_DEFAULT_FLAGS, HEXDSP_MAX_IN_LEN);
    g_rpc_out = rpcmem_alloc(RPCMEM_HEAP_ID_SYSTEM, RPCMEM_DEFAULT_FLAGS, HEXDSP_MAX_OUT_LEN);
    if (!g_rpc_in || !g_rpc_out) {
        fprintf(stderr, "hexdsp_offload: rpcmem_alloc for pre-allocated buffers failed\n");
        if (g_rpc_in)  { rpcmem_free(g_rpc_in);  g_rpc_in  = NULL; }
        if (g_rpc_out) { rpcmem_free(g_rpc_out); g_rpc_out = NULL; }
        hexdsp_offload_close(dsp_handle);
        dsp_handle = (remote_handle64)-1;
        rpcmem_deinit();
        rpcmem_ready = 0;
        return -1;
    }
    return 0;
}

// ---------------------------------------------------------------------------
// hexdsp_offload_shutdown — tear down.
// ---------------------------------------------------------------------------
int hexdsp_offload_shutdown(void)
{
    if (dsp_handle != (remote_handle64)-1) {
        hexdsp_offload_close(dsp_handle);
        dsp_handle = (remote_handle64)-1;
    }
    if (g_rpc_in)  { rpcmem_free(g_rpc_in);  g_rpc_in  = NULL; }
    if (g_rpc_out) { rpcmem_free(g_rpc_out); g_rpc_out = NULL; }
    if (rpcmem_ready) {
        rpcmem_deinit();
        rpcmem_ready = 0;
    }
    return 0;
}

// ---------------------------------------------------------------------------
// hexdsp_offload_process — main offload entry point.
//
// in/out are OAI-allocated buffers (e.g. stack or malloc).  We copy through
// pre-allocated ION bounce buffers so FastRPC can DMA-map them to the DSP
// without an extra kernel copy.  The OAI caller sees ordinary pointers.
// ---------------------------------------------------------------------------
int hexdsp_offload_process(const uint8_t *in,  uint32_t in_len,
                            uint8_t       *out, uint32_t out_len)
{
    if (!g_rpc_in || !g_rpc_out) {
        fprintf(stderr, "hexdsp_offload: buffers not ready — call hexdsp_offload_init() first\n");
        return -1;
    }
    if ((int)in_len > HEXDSP_MAX_IN_LEN || (int)out_len > HEXDSP_MAX_OUT_LEN) {
        fprintf(stderr, "hexdsp_offload: request too large (in=%u max=%d, out=%u max=%d)\n",
                in_len, HEXDSP_MAX_IN_LEN, out_len, HEXDSP_MAX_OUT_LEN);
        return -1;
    }

    memcpy(g_rpc_in, in, in_len);

    // FastRPC call: DMA-maps g_rpc_in/g_rpc_out to the DSP address space.
    int err = hexdsp_offload_run(dsp_handle,
                                  g_rpc_in,  (int)in_len,
                                  g_rpc_out, (int)out_len);
    if (err) {
        fprintf(stderr, "hexdsp_offload_run RPC failed: %d\n", err);
        return err;
    }

    memcpy(out, g_rpc_out, out_len);
    return 0;
}
