services:
    oai-gnb-10:
        image: ${REGISTRY-oaisoftwarealliance/}${GNB_IMG:-oai-gnb}:${TAG:-develop}
        network_mode: "host"
        container_name: oai-gnb
        cap_drop:
            - ALL
        cap_add:
            - SYS_NICE
            - IPC_LOCK
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
        volumes:
          - ../../conf_files/gnb.24.jetson.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "/opt/oai-gnb/bin/check-prach-io.sh"
            start_period: 15s
            start_interval: 500ms
            interval: 5s
            timeout: 5s
            retries: 5
    oai-gnb-20:
        image: ${REGISTRY-oaisoftwarealliance/}${GNB_IMG:-oai-gnb}:${TAG:-develop}
        network_mode: "host"
        container_name: oai-gnb
        cap_drop:
            - ALL
        cap_add:
            - SYS_NICE
            - IPC_LOCK
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
        volumes:
          - ../../conf_files/gnb.51.jetson.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "/opt/oai-gnb/bin/check-prach-io.sh"
            start_period: 15s
            start_interval: 500ms
            interval: 5s
            timeout: 5s
            retries: 5
    oai-gnb-30:
        image: ${REGISTRY-oaisoftwarealliance/}${GNB_IMG:-oai-gnb}:${TAG:-develop}
        network_mode: "host"
        container_name: oai-gnb
        cap_drop:
            - ALL
        cap_add:
            - SYS_NICE
            - IPC_LOCK
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
        volumes:
          - ../../conf_files/gnb.78.jetson.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "/opt/oai-gnb/bin/check-prach-io.sh"
            start_period: 15s
            start_interval: 500ms
            interval: 5s
            timeout: 5s
            retries: 5
    oai-gnb-40:
        image: ${REGISTRY-oaisoftwarealliance/}${GNB_IMG:-oai-gnb}:${TAG:-develop}
        network_mode: "host"
        container_name: oai-gnb
        cap_drop:
            - ALL
        cap_add:
            - SYS_NICE
            - IPC_LOCK
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
        volumes:
          - ../../conf_files/gnb.106.jetson.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "/opt/oai-gnb/bin/check-prach-io.sh"
            start_period: 15s
            start_interval: 500ms
            interval: 5s
            timeout: 5s
            retries: 5

