# SPDX-License-Identifier: LicenseRef-CSSL-1.0
#
# Dockerfile for OAI gNB with CSI per-RB logging
# Multi-stage build following OAI pattern
#

ARG UBUNTU_IMAGE=ubuntu:noble
FROM ran-base:latest AS gnb-base
FROM ran-build:latest AS gnb-build

# Build CSI logging library in builder
RUN cd /tmp && \
    git clone https://github.com/turletti/oai-csi-logging.git && \
    cd oai-csi-logging && \
    mkdir -p build && cd build && \
    cmake .. && \
    make && \
    make install && \
    ldconfig

# Start from scratch for final image
FROM ${UBUNTU_IMAGE} AS oai-gnb-csi

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris

RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install --yes \
        software-properties-common \
        procps \
        libsctp1 \
        libboost-chrono1.83.0 \
        libboost-date-time1.83.0 \
        libboost-filesystem1.83.0 \
        libboost-regex1.83.0 \
        libboost-serialization1.83.0 \
        libboost-thread1.83.0 \
        libboost-system1.83.0 \
        libboost-program-options1.83.0 \
        tzdata \
        libconfig9 \
        openssl \
        net-tools \
        iperf \
        iperf3 \
        iproute2 \
        iputils-ping \
        gdb \
        python3 \
        python3-six \
        python3-requests \
        libusb-1.0-0 \
        libyaml-cpp-dev \
        libnanomsg5 \
        libzmq5 \
        libpthread-stubs0-dev && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/oai-gnb/bin
COPY --from=gnb-build \
    /oai-ran/cmake_targets/ran_build/build/nr-softmodem ./
COPY ./docker/scripts/gnb_entrypoint.sh ./entrypoint.sh
COPY ./docker/scripts/check-prach-io.sh ./check-prach-io.sh

COPY --from=gnb-build \
    /oai-ran/cmake_targets/ran_build/build/liboai_eth_transpro.so \
    /oai-ran/cmake_targets/ran_build/build/librfsimulator.so \
    /oai-ran/cmake_targets/ran_build/build/liboai_usrpdevif.so \
    /oai-ran/cmake_targets/ran_build/build/liboai_bladerfdevif.so \
    /oai-ran/cmake_targets/ran_build/build/libcoding.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_libconfig.so \
    /oai-ran/cmake_targets/ran_build/build/libdfts.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc*.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv_ci.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_yaml.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv_bearer.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv_5Gue.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv_rrc.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv_o1.so \
    /oai-ran/cmake_targets/ran_build/build/libvrtsim.so \
    /oai-ran/cmake_targets/ran_build/build/liboai_zmqdevif.so \
    /usr/local/lib/

# Copy CSI logging library
COPY --from=gnb-build /usr/local/lib/libcsi_logging.so /usr/local/lib/

# Copy UHD and other dependencies from gnb-base
COPY --from=gnb-base /usr/local/bin/uhd_find_devices /usr/local/bin
COPY --from=gnb-base /usr/local/lib/libuhd.so.4.8.0 /usr/local/lib
COPY --from=gnb-base /usr/local/lib/uhd/utils/uhd_images_downloader.py /opt/oai-gnb/bin
COPY --from=gnb-build /usr/local/lib/flexric /usr/local/lib/flexric
COPY --from=gnb-base /usr/local/lib/libbladeRF* /usr/local/lib/

RUN /bin/bash -c "ln -s /usr/local/lib/liboai_usrpdevif.so /usr/local/lib/liboai_device.so" && \
    ldconfig

WORKDIR /opt/oai-gnb
COPY --from=gnb-base /usr/local/bin/yq /usr/local/bin/yq
COPY --from=gnb-base /tini /tini

ENTRYPOINT ["/tini", "-v", "--", "/opt/oai-gnb/bin/entrypoint.sh"]
CMD ["/opt/oai-gnb/bin/nr-softmodem"]
