FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libfftw3-dev \
    libconfig-dev \
    libusb-1.0-0-dev \
    liblapack-dev \
    libatlas-base-dev \
    libpthread-stubs0-dev \
    asn1c \
    bison \
    flex \
    libsctp-dev \
    lksctp-tools \
    libdouble-conversion-dev \
    libprotobuf-dev \
    protobuf-compiler \
    libssl-dev \
    pkg-config \
    autoconf \
    automake \
    libtool \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /oai

COPY . .

RUN git clone https://github.com/turletti/oai-csi-logging.git csi-logging && \
    cd csi-logging && mkdir -p build && cd build && \
    cmake .. && make && make install && ldconfig

WORKDIR /oai/build_oai

RUN cmake -DENABLE_ORAN=OFF -DENABLE_NFAPI=OFF .. && make -j4

CMD ["/bin/bash"]
