#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service
#   Valid for Ubuntu24.04
#
#---------------------------------------------------------------------

FROM ran-base:develop AS gnb-base

FROM ran-build:arm64 AS gnb-build


#start from scratch for target executable
FROM ubuntu:noble AS oai-gnb
ARG BUILD_OPTION
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris

RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install --yes \
        software-properties-common \
        procps \
        libsctp1 \
        libboost-chrono1.83.0 \
        libboost-date-time1.83.0 \
        libboost-filesystem1.83.0 \
        libboost-regex1.83.0 \
        libboost-serialization1.83.0 \
        libboost-thread1.83.0 \
        libboost-system1.83.0 \
        libboost-program-options1.83.0 \
        tzdata \
        libblas3 \
        libconfig9 \
        openssl \
        net-tools \
        iperf \
        iperf3 \
        iproute2 \
        iputils-ping \
        gdb \
        python3 \
        python3-six \
        python3-requests \
        libusb-1.0-0 \
        libyaml-cpp-dev \
        libnanomsg5 \
        # qemu for running arm64 binaries on amd64 
        qemu-system-aarch64 \
        qemu-utils \
        openssh-client \
        sshpass \
        iptables \
        binutils \
        netcat-openbsd \
        bridge-utils && \
# if the --sanitize option was used to build, additional packages are required
    /bin/bash -c 'if [[ "$BUILD_OPTION" = "--sanitize" ]]; then DEBIAN_FRONTEND=noninteractive apt-get install --yes \
        libasan8 \
        libubsan1 \
        liblapacke; fi' && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/oai-gnb/bin
COPY --from=gnb-build \
    /oai-ran/cmake_targets/ran_build/build-cross/nr-softmodem \
    /oai-ran/cmake_targets/ran_build/build-cross/*.so \
     ./
COPY ./docker/scripts/check-prach-io.sh ./check-prach-io.sh

WORKDIR /opt/oai-gnb
COPY ./docker/scripts/gnb_arm_qemu_entrypoint.sh ./entrypoint.sh
COPY --from=gnb-build \
    /oai-ran/qemu-rootfs/ \
    ./qemu-rootfs/ 
COPY --from=gnb-build \
    /oai-ran/start-qemu-tap-aarch64.sh ./start-qemu-tap-aarch64.sh
COPY --from=gnb-build \
    /oai-ran/setup-qemu-bridge.sh ./setup-qemu-bridge.sh
    
#EXPOSE 2152/udp  # S1U, GTP/UDP
#EXPOSE 22100/tcp # ?
#EXPOSE 36412/udp # S1C, SCTP/UDP
#EXPOSE 36422/udp # X2C, SCTP/UDP
#EXPOSE 50000/udp # IF5 / ORI (control)
#EXPOSE 50001/udp # IF5 / ECPRI (data)

# Share oai-ran on the network
RUN chown -R nobody:nogroup /opt/oai-gnb
RUN chmod -R 777 /opt/oai-gnb

#COPY --from=gnb-base /usr/local/bin/yq /usr/local/bin/yq
#COPY --from=gnb-base /tini /tini
#ENTRYPOINT ["/tini", "-v", "--", "/opt/oai-gnb/bin/entrypoint.sh"]
ENTRYPOINT ["/opt/oai-gnb/entrypoint.sh"]
#CMD ["/opt/oai-gnb/bin/nr-softmodem"]
