FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    gnuradio \
    python3-zmq \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY rotate_zmq.py send_freq_offset_zmq.py .